# Generated by Django 4.0.3 on 2022-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('cpf', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('birthdate', models.DateField(verbose_name='Nascimento')),
                ('phone_number', models.BigIntegerField(verbose_name='Telefone')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
            ],
        ),
    ]
